const WORDS = [
    { type: 'adv', word: 'TATSACHLICH', tr: 'справді / насправді', ex: 'Das ist tatsächlich wahr.' },
    { type: 'adv', word: 'EIGENTLICH', tr: 'власне / насправді', ex: 'Was willst du eigentlich?' },
    { type: 'adv', word: 'UNGEFAHR', tr: 'приблизно', ex: 'Es dauert ungefähr eine Stunde.' },
    { type: 'adv', word: 'NORMALERWEISE', tr: 'зазвичай', ex: 'Normalerweise komme ich pünktlich.' },
    { type: 'adv', word: 'MEISTENS', tr: 'найчастіше', ex: 'Ich esse meistens zu Hause.' },
    { type: 'adv', word: 'MANCHMAL', tr: 'іноді', ex: 'Manchmal bin ich müde.' },
    { type: 'adv', word: 'SELTEN', tr: 'рідко', ex: 'Er kommt selten zu spät.' },
    { type: 'adv', word: 'SOFORT', tr: 'одразу / негайно', ex: 'Ich komme sofort!' },
    { type: 'adv', word: 'PLOTZLICH', tr: 'раптово', ex: 'Plötzlich wurde es dunkel.' },
    { type: 'adv', word: 'INZWISCHEN', tr: 'тим часом', ex: 'Inzwischen wohne ich in Berlin.' },
    { type: 'adv', word: 'SEITDEM', tr: 'з того часу', ex: 'Seitdem habe ich ihn nicht gesehen.' },
    { type: 'adv', word: 'VORHIN', tr: 'щойно / нещодавно', ex: 'Ich war vorhin beim Arzt.' },
    { type: 'adv', word: 'NACHHER', tr: 'потім / після', ex: 'Wir reden nachher darüber.' },
    { type: 'adv', word: 'UBRIGENS', tr: 'до речі', ex: 'Übrigens, morgen ist Montag.' },
    { type: 'adv', word: 'TROTZDEM', tr: 'все одно / незважаючи', ex: 'Es regnet, trotzdem gehe ich.' },
    { type: 'adv', word: 'DESHALB', tr: 'тому / через це', ex: 'Er ist krank, deshalb bleibt er.' },
    { type: 'adv', word: 'DESWEGEN', tr: 'через це / тому', ex: 'Deswegen bin ich hier.' },
    { type: 'adv', word: 'DENNOCH', tr: 'проте / все ж таки', ex: 'Dennoch hat er gewonnen.' },
    { type: 'adv', word: 'ALLERDINGS', tr: 'однак / щоправда', ex: 'Es ist schön, allerdings teuer.' },
    { type: 'adv', word: 'JEDENFALLS', tr: 'у будь-якому разі', ex: 'Jedenfalls war es interessant.' },
    { type: 'adv', word: 'MINDESTENS', tr: 'щонайменше', ex: 'Es dauert mindestens zwei Stunden.' },
    { type: 'adv', word: 'WENIGSTENS', tr: 'принаймні', ex: 'Wenigstens hat es nicht geregnet.' },
    { type: 'adv', word: 'ZIEMLICH', tr: 'досить / доволі', ex: 'Das Essen war ziemlich gut.' },
    { type: 'adv', word: 'BESONDERS', tr: 'особливо', ex: 'Das gefällt mir besonders gut.' },
    { type: 'adv', word: 'KAUM', tr: 'ледве / ледь', ex: 'Ich kann das kaum glauben.' },
    { type: 'adv', word: 'FAST', tr: 'майже', ex: 'Ich bin fast fertig.' },
    { type: 'adv', word: 'INSGESAMT', tr: 'загалом / всього', ex: 'Das kostet insgesamt 50 Euro.' },
    { type: 'adv', word: 'DABEI', tr: 'при цьому / поруч', ex: 'Ich war dabei, als es passierte.' },
    { type: 'adv', word: 'DAZU', tr: 'до цього / крім того', ex: 'Ich habe nichts dazu gesagt.' },
    { type: 'adv', word: 'BEREITS', tr: 'вже / ще раніше', ex: 'Ich habe das bereits gemacht.' },
    { type: 'part', word: 'DOCH', tr: 'ж / але ж / таки', ex: 'Das weißt du doch!' },
    { type: 'part', word: 'DENN', tr: 'же (у питаннях)', ex: 'Was machst du denn hier?' },
    { type: 'part', word: 'MAL', tr: 'но / будь ласка', ex: 'Kannst du mal helfen?' },
    { type: 'part', word: 'HALT', tr: 'ну от / так вже є', ex: 'Das ist halt so.' },
    { type: 'part', word: 'EBEN', tr: 'саме / ну ось', ex: 'Das ist eben das Problem.' },
    { type: 'part', word: 'JA', tr: 'ж / адже (підсилення)', ex: 'Das ist ja interessant!' },
    { type: 'part', word: 'WOHL', tr: 'мабуть / мусить бути', ex: 'Er ist wohl krank.' },
    { type: 'part', word: 'SCHON', tr: 'вже / та вже', ex: 'Das wird schon klappen.' },
    { type: 'part', word: 'RUHIG', tr: 'спокійно / сміливо', ex: 'Du kannst ruhig gehen.' },
    { type: 'part', word: 'BLOSS', tr: 'тільки / же', ex: 'Mach das bloß nicht!' },
    { type: 'part', word: 'NUR', tr: 'тільки / лише', ex: 'Komm nur herein!' },
    { type: 'part', word: 'ETWA', tr: 'невже / хіба', ex: 'Bist du etwa müde?' },
    { type: 'part', word: 'SOGAR', tr: 'навіть', ex: 'Er spricht sogar Russisch.' },
    { type: 'part', word: 'ZUMINDEST', tr: 'принаймні', ex: 'Zumindest hat er angerufen.' },
    { type: 'part', word: 'IMMERHIN', tr: 'все ж таки', ex: 'Immerhin hat er es versucht.' },
    { type: 'konj', word: 'OBWOHL', tr: 'хоча / незважаючи', ex: 'Obwohl er müde war, arbeitete er.' },
    { type: 'konj', word: 'WAHREND', tr: 'поки / тоді як', ex: 'Während ich koche, liest er.' },
    { type: 'konj', word: 'NACHDEM', tr: 'після того як', ex: 'Nachdem er gegessen hatte, schlief er.' },
    { type: 'konj', word: 'SOBALD', tr: 'щойно / як тільки', ex: 'Sobald er kommt, rufe ich an.' },
    { type: 'konj', word: 'SOLANGE', tr: 'поки / доки', ex: 'Solange ich hier bin, bin ich glücklich.' },
    { type: 'konj', word: 'DAMIT', tr: 'щоб (мета)', ex: 'Ich erkläre es, damit du verstehst.' },
    { type: 'konj', word: 'FALLS', tr: 'якщо / у разі якщо', ex: 'Falls du kommst, ruf an.' },
    { type: 'konj', word: 'SOFERN', tr: 'за умови що', ex: 'Sofern es klappt, fahren wir.' },
    { type: 'konj', word: 'BEVOR', tr: 'перед тим як', ex: 'Bevor du gehst, sag mir Bescheid.' },
    { type: 'konj', word: 'SODASS', tr: 'так що / тому що', ex: 'Er ist krank, sodass er bleibt.' },
    { type: 'konj', word: 'ENTWEDER', tr: 'або... або', ex: 'Entweder kommst du, oder ich gehe.' },
    { type: 'konj', word: 'WEDER', tr: 'ні... ні', ex: 'Das ist weder gut noch schlecht.' },
    { type: 'konj', word: 'SONDERN', tr: 'а (після заперечення)', ex: 'Nicht ich, sondern er hat recht.' },
    { type: 'konj', word: 'ZWAR', tr: 'хоча й / правда', ex: 'Das ist zwar teuer, aber gut.' },
    { type: 'konj', word: 'INDEM', tr: 'тим що / шляхом того', ex: 'Er lernt, indem er liest.' },
    { type: 'adj', word: 'ZUFRIEDEN', tr: 'задоволений', ex: 'Ich bin damit zufrieden.' },
    { type: 'adj', word: 'NEUGIERIG', tr: 'цікавий / допитливий', ex: 'Er ist sehr neugierig.' },
    { type: 'adj', word: 'ZUVERLASSIG', tr: 'надійний', ex: 'Sie ist eine zuverlässige Kollegin.' },
    { type: 'adj', word: 'ENTSPANNT', tr: 'розслаблений / спокійний', ex: 'Nach dem Urlaub bin ich entspannt.' },
    { type: 'adj', word: 'AUFGEREGT', tr: 'схвильований', ex: 'Die Kinder sind ganz aufgeregt.' },
    { type: 'adj', word: 'ENTTAUSCHT', tr: 'розчарований', ex: 'Ich bin enttäuscht von ihm.' },
    { type: 'adj', word: 'STOLZ', tr: 'гордий', ex: 'Sie ist stolz auf ihren Sohn.' },
    { type: 'adj', word: 'NERVOS', tr: 'нервовий', ex: 'Vor dem Test bin ich nervös.' },
    { type: 'adj', word: 'GLEICHZEITIG', tr: 'одночасний / водночас', ex: 'Das kann ich nicht gleichzeitig.' },
    { type: 'adj', word: 'GEWOHNT', tr: 'звичний / призвичаєний', ex: 'Ich bin das gewohnt.' },
    { type: 'adj', word: 'BESORGT', tr: 'стурбований', ex: 'Die Eltern sind besorgt.' },
    { type: 'adj', word: 'ERSTAUNT', tr: 'здивований', ex: 'Ich bin erstaunt über die Nachricht.' },
    { type: 'adj', word: 'SELBSTANDIG', tr: 'самостійний', ex: 'Sie arbeitet selbständig.' },
    { type: 'adj', word: 'VERTRAUT', tr: 'знайомий / близький', ex: 'Das kommt mir vertraut vor.' },
    { type: 'adj', word: 'AUSREICHEND', tr: 'достатній', ex: 'Das ist ausreichend für uns.' },
    { type: 'phrase', word: 'ZUNACHST', tr: 'спочатку / передусім', ex: 'Zunächst müssen wir planen.' },
    { type: 'phrase', word: 'SCHLIESSLICH', tr: 'зрештою / нарешті', ex: 'Schließlich haben wir es geschafft.' },
    { type: 'phrase', word: 'EINERSEITS', tr: 'з одного боку', ex: 'Einerseits ist es teuer.' },
    { type: 'phrase', word: 'ANDERERSEITS', tr: 'з іншого боку', ex: 'Andererseits ist es praktisch.' },
    { type: 'phrase', word: 'IMGRUNDE', tr: 'по суті / власне', ex: 'Im Grunde bin ich einverstanden.' },
    { type: 'phrase', word: 'NEBENBEI', tr: 'між іншим / паралельно', ex: 'Nebenbei arbeite ich als Kellner.' },
    { type: 'phrase', word: 'SOZUSAGEN', tr: 'так би мовити', ex: 'Er ist sozusagen mein Chef.' },
    { type: 'phrase', word: 'KEINESFALLS', tr: 'жодним чином', ex: 'Das darf keinesfalls passieren.' },
    { type: 'phrase', word: 'GERADEZU', tr: 'прямо-таки / мало не', ex: 'Das ist geradezu unglaublich.' },
    { type: 'phrase', word: 'ANSONSTEN', tr: 'інакше / а так', ex: 'Ansonsten läuft alles gut.' },
    { type: 'phrase', word: 'VORAUSSICHTLICH', tr: 'очевидно / за прогнозом', ex: 'Er kommt voraussichtlich morgen.' },
    { type: 'phrase', word: 'INWIEFERN', tr: 'якою мірою / наскільки', ex: 'Inwiefern hilft das?' },
    { type: 'phrase', word: 'MITUNTER', tr: 'інколи / часом', ex: 'Das passiert mitunter.' },
    { type: 'phrase', word: 'DEMENTSPRECHEND', tr: 'відповідно до цього', ex: 'Dementsprechend handeln wir.' },
    { type: 'phrase', word: 'UNVERZUGLICH', tr: 'негайно / без зволікань', ex: 'Bitte unverzüglich antworten.' },
    { type: 'phrase', word: 'IMMERWIEDER', tr: 'знову і знову', ex: 'Er macht immer wieder Fehler.' },
    { type: 'phrase', word: 'INDERTAT', tr: 'справді / дійсно', ex: 'Das ist in der Tat schwierig.' },
    { type: 'phrase', word: 'DEMZUFOLGE', tr: 'отже / звідси виходить', ex: 'Demzufolge ist er schuldig.' },
    { type: 'phrase', word: 'INFOLGEDESSEN', tr: 'внаслідок цього', ex: 'Infolgedessen mussten wir warten.' },
    { type: 'phrase', word: 'NICHTSDESTOTROTZ', tr: 'незважаючи на це', ex: 'Nichtsdestotrotz machen wir weiter.' },
    { type: 'phrase', word: 'IMALLGEMEINEN', tr: 'загалом кажучи', ex: 'Im Allgemeinen ist es gut.' },
];